# Generated by Django 4.2.4 on 2023-08-12 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CampDetail",
            fields=[
                (
                    "camp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="camp.camp",
                    ),
                ),
                ("visibility", models.CharField(blank=True, max_length=150)),
                ("ashore", models.CharField(blank=True, max_length=150)),
                ("number_tents", models.IntegerField(blank=True)),
                ("firewood", models.CharField(blank=True, max_length=150)),
                ("conveniences", models.CharField(blank=True, max_length=150)),
                ("connection", models.CharField(blank=True, max_length=150)),
                ("mosquitoes", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("pht_from_water", models.ImageField(blank=True, upload_to="static/")),
                ("pht_camping", models.ImageField(blank=True, upload_to="static/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherPht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/")),
                (
                    "camp_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camp.campdetail",
                    ),
                ),
            ],
        ),
    ]
