# Generated by Django 4.2.4 on 2023-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campdetail",
            name="ashore",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="connection",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="conveniences",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="firewood",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="mosquitoes",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="number_tents",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="pht_camping",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="pht_from_water",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="visibility",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
