# Generated by Django 4.2.4 on 2023-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0002_alter_campdetail_ashore_alter_campdetail_connection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campdetail",
            name="pht_camping",
            field=models.ImageField(blank=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="campdetail",
            name="pht_from_water",
            field=models.ImageField(blank=True, upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="otherpht",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
